wandb_version: 1

in_dim:
  desc: null
  value: 8
out_dim:
  desc: null
  value: 1
ntrain:
  desc: null
  value: 300
nvalid:
  desc: null
  value: 200
dataset:
  desc: null
  value:
  - 1
  - 2
  - 3
  - 5
  - 10
work_path:
  desc: null
  value: work\Trans_test_8
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 801
learning_rate:
  desc: null
  value: 0.001
scheduler_step:
  desc: null
  value: 700
scheduler_gamma:
  desc: null
  value: 0.1
pred_model_dict:
  desc: null
  value:
    node_feats: 16
    pos_dim: 2
    n_targets: 1
    n_hidden: 64
    num_feat_layers: 0
    num_encoder_layers: 3
    n_head: 4
    dim_feedforward: 128
    attention_type: galerkin
    feat_extract_type: None
    xavier_init: 0.01
    diagonal_weight: 0.01
    symmetric_init: false
    layer_norm: true
    attn_norm: false
    norm_eps: 1.0e-07
    batch_norm: false
    return_attn_weight: false
    return_latent: false
    decoder_type: ifft
    last_activation: false
    freq_dim: 64
    num_regressor_layers: 1
    regressor_activation: gelu
    fourier_modes: 16
    spacial_dim: 2
    spacial_fc: true
    dropout: 0.0
    encoder_dropout: 0.0
    decoder_dropout: 0.0
    ffn_dropout: 0.0
    debug: false
    upsample_mode: interp
    downsample_mode: interp
    boundary_condition: dirichlet
super_model_dict:
  desc: null
  value:
    modes:
    - 16
    - 16
    width: 64
    depth: 2
    steps: 1
    padding: 8
    dropout: 0.0
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705320493.34902
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
