Rotor37_2d:
  node_feats: 28
  pos_dim: 2
  n_targets: 64
  n_hidden: 128
  num_feat_layers: 0
  num_encoder_layers: 3
  n_head: 4
  dim_feedforward: 128
  attention_type: galerkin
  feat_extract_type: None
  xavier_init: 0.01
  diagonal_weight: 0.01
  symmetric_init: False
  layer_norm: True
  attn_norm: False
  norm_eps: 0.0000001
  batch_norm: False
  return_attn_weight: False
  return_latent: False
  decoder_type: ifft
  last_activation: False
  freq_dim: 64
  num_regressor_layers: 1
  regressor_activation: gelu
  fourier_modes: 16
  spacial_dim: 2
  spacial_fc: True
  dropout: 0.0
  encoder_dropout: 0.0
  decoder_dropout: 0.0
  ffn_dropout: 0.00
  debug: False
  upsample_mode: interp
  downsample_mode: interp
  boundary_condition: dirichlet
