wandb_version: 1

in_dim:
  desc: null
  value: 16
out_dim:
  desc: null
  value: 1
ntrain:
  desc: null
  value: 700
nvalid:
  desc: null
  value: 200
dataset:
  desc: null
  value:
  - 1
  - 2
  - 3
  - 5
  - 10
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 801
learning_rate:
  desc: null
  value: 0.001
scheduler_step:
  desc: null
  value: 700
scheduler_gamma:
  desc: null
  value: 0.1
modes:
  desc: null
  value:
  - 32
  - 32
width:
  desc: null
  value: 64
depth:
  desc: null
  value: 4
steps:
  desc: null
  value: 1
padding:
  desc: null
  value: 8
dropout:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704718531.989769
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
