Darcy_2d:
  node_feats: 1
  pos_dim: 2
  n_targets: 1
  n_hidden: 128
  num_feat_layers: 0
  num_encoder_layers: 6
  n_head: 4
  dim_feedforward: 256
  feat_extract_type: null
  attention_type: galerkin
  xavier_init: 0.01
  diagonal_weight: 0.01
  symmetric_init: False
  layer_norm: False
  attn_norm: True
  norm_eps: 0.0000001
  batch_norm: False
  return_attn_weight: False
  return_latent: False
  decoder_type: ifft
  spacial_dim: 2
  spacial_fc: True
  upsample_mode: interp
  downsample_mode: interp
  freq_dim: 32
  boundary_condition: dirichlet
  num_regressor_layers: 2
  fourier_modes: 12
  regressor_activation: silu
  downscaler_activation: relu
  upscaler_activation: silu
  last_activation: True
  dropout: 0.0
  downscaler_dropout: 0.05
  upscaler_dropout: 0.0
  ffn_dropout: 0.05
  encoder_dropout: 0.05
  decoder_dropout: 0
  debug: False

Darcy_2d_inverse:
  subsample_nodes: 3
  subsample_attn: 12
  gamma: 0.0
  noise: 0.01
  inverse: True
  node_feats: 1
  pos_dim: 2
  n_targets: 1
  n_hidden: 192
  num_feat_layers: 0
  num_encoder_layers: 6
  n_head: 4
  dim_feedforward: 384
  feat_extract_type: null
  attention_type: galerkin
  xavier_init: 0.01
  diagonal_weight: 0.01
  symmetric_init: False
  layer_norm: False
  attn_norm: True
  norm_eps: 0.0000001
  batch_norm: False
  return_attn_weight: False
  return_latent: False
  decoder_type: ifft
  regressor_activation: silu
  spacial_dim: 2
  spacial_fc: True
  freq_dim: 32
  num_regressor_layers: 2
  fourier_modes: 12
  last_activation: True
  upsample_mode: interp
  downsample_mode: interp
  boundary_condition: free
  dropout: 0.05
  downscaler_dropout: 0.05
  upscaler_dropout: 0.0
  ffn_dropout: 0.05
  encoder_dropout: 0.05
  decoder_dropout: 0.0
  debug: False