wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: MLP
dataset:
  desc: null
  value: MNIST
epochs:
  desc: null
  value: 30
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704697246.611679
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
