Turbulence_2d+t:
  node_feats: 10+2
  pos_dim: 2
  n_targets: 1
  n_hidden: 48
  num_feat_layers: 0
  num_encoder_layers: 4
  n_head: 1
  dim_feedforward: 96
  attention_type: galerkin
  feat_extract_type: None
  xavier_init: 0.01
  diagonal_weight: 0.01
  layer_norm: True
  attn_norm: False
  return_attn_weight: False
  return_latent: False
  decoder_type: ifft
  freq_dim: 20
  num_regressor_layers: 2
  fourier_modes: 12
  spacial_dim: 2
  spacial_fc: False
  dropout: 0.0
  encoder_dropout: 0.0
  decoder_dropout: 0.0
  ffn_dropout: 0.05
  debug: False