BladeFlutter_2d:
  node_feats: 4
  pos_dim: 3
  n_targets: 3
  n_hidden: 48
  num_feat_layers: 2
  num_encoder_layers: 4
  n_head: 1
  dim_feedforward: 96
  attention_type: galerkin
  feat_extract_type: None
  xavier_init: 0.01
  diagonal_weight: 0.01
  symmetric_init: False
  layer_norm: True
  attn_norm: False
  norm_eps: 0.0000001
  batch_norm: False
  return_attn_weight: False
  return_latent: False
  decoder_type: ifft2
  last_activation: True
  freq_dim: 16
  num_regressor_layers: 2
  fourier_modes: 16
  spacial_dim: 3
  spacial_fc: False
  dropout: 0.0
  encoder_dropout: 0.0
  decoder_dropout: 0.0
  ffn_dropout: 0.05
  debug: False
  upsample_mode: interp
  downsample_mode: interp
  boundary_condition: dirichlet